// miniapp/jumulu/src/pages/mine/account-status.vue
<script setup lang="ts">
import { ref } from 'vue'
import { onPullDownRefresh, onShow } from '@dcloudio/uni-app'
import PageIntro from '../../components/PageIntro.vue'
import type { AccountStatus } from '../../types'
import { apiRequest, readAuth } from '../../utils/api'

type Notice = {
  id: string
  title: string
  content: string
  read_at?: string | null
  created_at: string
}

const status = ref<AccountStatus | null>(null)
const notices = ref<Notice[]>([])
const content = ref('')
const evidenceText = ref('')
const loading = ref(false)
const submitting = ref(false)
const error = ref('')

function formatDate(value?: string | null) {
  if (!value) return '长期有效'
  const date = new Date(value)
  if (!Number.isFinite(date.getTime())) return value
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`
}

function appealLabel(value?: string) {
  if (value === 'pending') return '处理中'
  if (value === 'needs_info') return '待补充'
  if (value === 'approved') return '已通过'
  if (value === 'rejected') return '维持限制'
  return '未提交'
}

async function load() {
  if (!readAuth()?.token) {
    status.value = null; notices.value = []; error.value = '请先登录'
    uni.stopPullDownRefresh()
    return
  }
  loading.value = true; error.value = ''
  try {
    const [nextStatus, nextNotices] = await Promise.all([
      apiRequest<AccountStatus>('/lc/account/status'),
      apiRequest<Notice[]>('/lc/account/notifications'),
    ])
    status.value = nextStatus
    notices.value = nextNotices
    if (nextStatus.appeal?.status === 'needs_info') {
      content.value = nextStatus.appeal.content || ''
      evidenceText.value = (nextStatus.appeal.evidence_urls || []).join('\n')
    }
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : '账号状态加载失败'
  } finally {
    loading.value = false
    uni.stopPullDownRefresh()
  }
}

async function submitAppeal() {
  if (content.value.trim().length < 10 || submitting.value) return
  submitting.value = true; error.value = ''
  try {
    const evidenceUrls = evidenceText.value.split(/\r?\n/).map(item => item.trim()).filter(Boolean).slice(0, 6)
    await apiRequest('/lc/account/appeals', {
      method: 'POST',
      data: { content: content.value.trim(), evidenceUrls },
    })
    content.value = ''; evidenceText.value = ''
    uni.showToast({ title: '申诉已提交', icon: 'success' })
    await load()
  } catch (reason) {
    error.value = reason instanceof Error ? reason.message : '申诉提交失败'
  } finally { submitting.value = false }
}

async function markRead(item: Notice) {
  if (item.read_at) return
  try {
    await apiRequest(`/lc/account/notifications/${encodeURIComponent(item.id)}/read`, { method: 'PUT' })
    item.read_at = new Date().toISOString()
  } catch { /* 下次进入时仍会显示未读 */ }
}

onShow(() => void load())
onPullDownRefresh(load)
</script>

<template>
  <view class="page">
    <PageIntro eyebrow="账号治理" nav-title="账号通知与申诉" title="账号状态" description="限制原因、申诉进度和管理员回复都在这里留痕。" />
    <view v-if="loading" class="surface state-card"><text class="muted">正在读取账号状态...</text></view>
    <view v-if="error" class="surface error-card"><text>{{ error }}</text></view>

    <view v-if="status && status.state !== 'merged'" class="surface state-card" :class="{ restricted: status.state === 'restricted' }">
      <view class="state-head">
        <view>
          <text class="eyebrow">{{ status.state === 'restricted' ? '当前受限' : '状态正常' }}</text>
          <text class="state-title">{{ status.restriction?.scope === 'account' ? '账号功能限制' : status.restriction ? '发布功能限制' : '账号可以正常使用' }}</text>
        </view>
        <text v-if="status.restriction" class="state-tag">{{ status.restriction.ends_at ? '限时' : '长期' }}</text>
      </view>
      <view v-if="status.restriction" class="state-detail">
        <text><strong>原因：</strong>{{ status.restriction.reason }}</text>
        <text><strong>开始：</strong>{{ formatDate(status.restriction.starts_at) }}</text>
        <text><strong>结束：</strong>{{ formatDate(status.restriction.ends_at) }}</text>
      </view>
    </view>

    <view v-if="status?.state === 'restricted'" class="surface appeal-card">
      <view class="section-head"><text class="section-title compact">账号申诉</text><text v-if="status.appeal" class="muted small">{{ appealLabel(status.appeal.status) }}</text></view>
      <view v-if="status.appeal?.admin_reply" class="reply"><strong>管理员回复：</strong>{{ status.appeal.admin_reply }}</view>
      <template v-if="!status.appeal || status.appeal.status === 'needs_info' || ['approved', 'rejected', 'withdrawn'].includes(status.appeal.status)">
        <text class="field-label">申诉说明</text>
        <textarea v-model="content" class="textarea" maxlength="2000" placeholder="说明具体情况、相关时间和希望如何处理，至少 10 个字。" />
        <text class="field-label">补充材料链接（可选）</text>
        <textarea v-model="evidenceText" class="textarea evidence" placeholder="每行一个链接，最多 6 个" />
        <button class="primary-button submit" :loading="submitting" :disabled="submitting || content.trim().length < 10" @tap="submitAppeal">{{ status.appeal?.status === 'needs_info' ? '补充并重新提交' : '提交申诉' }}</button>
      </template>
      <text v-else-if="status.appeal?.status === 'pending'" class="muted pending">申诉正在处理中，不需要重复提交。</text>
    </view>

    <view class="surface notices">
      <text class="section-title compact">账号通知</text>
      <text v-if="notices.length === 0" class="muted empty">暂无账号治理通知。</text>
      <view v-for="item in notices" :key="item.id" class="notice" @tap="markRead(item)">
        <view class="notice-title"><strong>{{ item.title }}</strong><text v-if="!item.read_at">未读</text></view>
        <text class="notice-content">{{ item.content }}</text>
        <text class="notice-time">{{ formatDate(item.created_at) }}</text>
      </view>
    </view>
  </view>
</template>

<style scoped>
.state-card, .appeal-card, .notices, .error-card { margin-top: 14rpx; padding: 20rpx; }
.error-card { border-color: #efc9c5; background: #fff6f5; color: #a53232; }
.state-card.restricted { border-color: #e6bc77; background: #fffaf2; }
.state-head, .section-head, .notice-title { display: flex; align-items: flex-start; justify-content: space-between; gap: 14rpx; }
.eyebrow, .state-title { display: block; }
.eyebrow { color: #166534; font-size: 21rpx; font-weight: 850; }
.restricted .eyebrow { color: #8b5919; }
.state-title { margin-top: 6rpx; color: #1f2937; font-size: 30rpx; font-weight: 900; }
.state-tag { padding: 7rpx 12rpx; border-radius: 8rpx; background: #fff4e6; color: #8b5919; font-size: 21rpx; font-weight: 850; }
.state-detail { display: grid; gap: 8rpx; margin-top: 18rpx; color: #667085; font-size: 23rpx; line-height: 1.6; }
.section-title.compact { margin: 0; font-size: 28rpx; }
.small { font-size: 22rpx; }
.reply { margin-top: 16rpx; padding: 16rpx; border-radius: 8rpx; background: #eff6ff; color: #275389; font-size: 23rpx; line-height: 1.65; }
.textarea { min-height: 190rpx; }
.textarea.evidence { min-height: 120rpx; }
.submit { width: 100%; margin-top: 18rpx; }
.pending, .empty { display: block; margin-top: 16rpx; font-size: 23rpx; line-height: 1.6; }
.notices { padding-top: 20rpx; padding-bottom: 4rpx; }
.notice { padding: 20rpx 0; border-top: 1rpx solid #eceff2; }
.notice:first-of-type { margin-top: 14rpx; }
.notice-title strong { color: #27364a; font-size: 25rpx; }
.notice-title text { color: #9a651e; font-size: 20rpx; font-weight: 850; }
.notice-content, .notice-time { display: block; }
.notice-content { margin-top: 8rpx; color: #64748b; font-size: 22rpx; line-height: 1.65; }
.notice-time { margin-top: 7rpx; color: #98a2b3; font-size: 20rpx; }
</style>

// src/pages/AccountStatus.tsx
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { JumuluCompactHeader, JumuluPageFrame } from '../components/JumuluPageChrome';
import { readStoredCreatorAuth } from '../lib/authSession';

type Restriction = {
  id?: string | null;
  scope: 'publish' | 'account';
  reason: string;
  starts_at?: string | null;
  ends_at?: string | null;
};

type Appeal = {
  id: string;
  content: string;
  evidence_urls?: string[];
  status: 'pending' | 'needs_info' | 'approved' | 'rejected' | 'withdrawn';
  admin_reply?: string | null;
  created_at: string;
};

type Notice = {
  id: string;
  type: string;
  title: string;
  content: string;
  read_at?: string | null;
  created_at: string;
};

type StatusPayload = {
  state: 'active' | 'restricted' | 'merged';
  message: string;
  restriction: Restriction | null;
  appeal: Appeal | null;
  unread_count: number;
};

const INK = '#1f2937';
const MUTED = 'rgba(71,85,105,0.76)';
const LINE = 'rgba(217,168,87,0.24)';

function dateTime(value?: string | null) {
  if (!value) return '';
  const date = new Date(value);
  return Number.isFinite(date.getTime()) ? date.toLocaleString('zh-CN', { hour12: false }) : value;
}

function appealStatusLabel(status?: Appeal['status']) {
  if (status === 'pending') return '处理中';
  if (status === 'needs_info') return '待补充';
  if (status === 'approved') return '已通过';
  if (status === 'rejected') return '维持限制';
  return '未提交';
}

export default function AccountStatus() {
  const auth = readStoredCreatorAuth();
  const token = auth?.token || '';
  const [status, setStatus] = useState<StatusPayload | null>(null);
  const [notices, setNotices] = useState<Notice[]>([]);
  const [content, setContent] = useState('');
  const [evidenceText, setEvidenceText] = useState('');
  const [loading, setLoading] = useState(Boolean(auth?.token));
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const load = useCallback(async () => {
    if (!token) return;
    setLoading(true);
    setError('');
    try {
      const headers = { Authorization: `Bearer ${token}` };
      const [statusResponse, noticeResponse] = await Promise.all([
        fetch('/api/lc/account/status', { headers }),
        fetch('/api/lc/account/notifications', { headers }),
      ]);
      const [statusBody, noticeBody] = await Promise.all([statusResponse.json(), noticeResponse.json()]);
      if (!statusResponse.ok || !statusBody.success) throw new Error(statusBody.error || '账号状态加载失败');
      setStatus(statusBody.data);
      if (noticeResponse.ok && noticeBody.success) setNotices(noticeBody.data || []);
      if (statusBody.data?.appeal?.status === 'needs_info') {
        setContent(statusBody.data.appeal.content || '');
        setEvidenceText((statusBody.data.appeal.evidence_urls || []).join('\n'));
      }
      if (statusBody.data?.state === 'merged') {
        localStorage.removeItem('lc_creator');
        localStorage.removeItem('lc_admin_token');
        window.dispatchEvent(new Event('lc-auth-changed'));
      }
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : '账号状态加载失败');
    } finally { setLoading(false); }
  }, [token]);

  useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, [load]);

  const submitAppeal = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!token || content.trim().length < 10) return;
    setSubmitting(true);
    setError('');
    try {
      const evidenceUrls = evidenceText.split(/\r?\n/).map(item => item.trim()).filter(Boolean).slice(0, 6);
      const response = await fetch('/api/lc/account/appeals', {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: content.trim(), evidenceUrls }),
      });
      const body = await response.json();
      if (!response.ok || !body.success) throw new Error(body.error || '申诉提交失败');
      setContent('');
      setEvidenceText('');
      await load();
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : '申诉提交失败');
    } finally { setSubmitting(false); }
  };

  const markRead = async (id: string) => {
    if (!token) return;
    const response = await fetch(`/api/lc/account/notifications/${encodeURIComponent(id)}/read`, {
      method: 'PUT',
      headers: { Authorization: `Bearer ${token}` },
    });
    if (response.ok) setNotices(current => current.map(item => item.id === id ? { ...item, read_at: new Date().toISOString() } : item));
  };

  if (!auth?.token) return (
    <JumuluPageFrame currentLabel="账号状态" maxWidth={900}>
      <JumuluCompactHeader title="账号状态" description="登录后可以查看限制原因、站内通知和申诉处理结果。" />
      <section style={panelStyle}>
        <p style={{ margin: 0, color: MUTED, lineHeight: 1.7 }}>当前没有登录。</p>
        <Link to="/login?redirect=%2Faccount-status" style={primaryLinkStyle}>登录账号</Link>
      </section>
    </JumuluPageFrame>
  );

  return (
    <JumuluPageFrame currentLabel="账号状态" maxWidth={900}>
      <JumuluCompactHeader title="账号状态与申诉" description="限制原因、处理时间和管理员回复都在这里留痕。" />
      {loading && <section style={panelStyle}>正在读取账号状态...</section>}
      {error && <section style={{ ...panelStyle, borderColor: 'rgba(185,28,28,0.24)', color: '#991b1b' }}>{error}</section>}
      {status?.state === 'merged' && (
        <section style={panelStyle}>
          <h2 style={titleStyle}>临时账号已合并</h2>
          <p style={bodyStyle}>{status.message}</p>
          <Link to="/login?redirect=%2Faccount-status" style={primaryLinkStyle}>重新登录原网站账号</Link>
        </section>
      )}
      {status && status.state !== 'merged' && (
        <section style={{ ...panelStyle, borderColor: status.state === 'restricted' ? 'rgba(180,83,9,0.30)' : LINE, background: status.state === 'restricted' ? '#fffaf2' : '#fff' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'flex-start', flexWrap: 'wrap' }}>
            <div>
              <div style={{ color: status.state === 'restricted' ? '#925f18' : '#166534', fontSize: 12, fontWeight: 900 }}>{status.state === 'restricted' ? '当前受限' : '状态正常'}</div>
              <h2 style={{ ...titleStyle, marginTop: 5 }}>{status.restriction?.scope === 'account' ? '账号功能限制' : status.restriction ? '发布功能限制' : '账号可以正常使用'}</h2>
            </div>
            {status.restriction && <span style={{ padding: '5px 9px', borderRadius: 6, background: '#fff4e6', color: '#925f18', fontSize: 12, fontWeight: 900 }}>{status.restriction.ends_at ? '限时' : '长期'}</span>}
          </div>
          {status.restriction && (
            <div style={{ display: 'grid', gap: 8, marginTop: 14, color: MUTED, fontSize: 13, lineHeight: 1.65 }}>
              <div><strong style={{ color: INK }}>原因：</strong>{status.restriction.reason}</div>
              <div><strong style={{ color: INK }}>开始：</strong>{dateTime(status.restriction.starts_at) || '未记录'}</div>
              <div><strong style={{ color: INK }}>结束：</strong>{dateTime(status.restriction.ends_at) || '长期有效，等待管理员解除'}</div>
            </div>
          )}
        </section>
      )}

      {status?.state === 'restricted' && (
        <section style={panelStyle}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
            <h2 style={titleStyle}>账号申诉</h2>
            {status.appeal && <span style={{ color: MUTED, fontSize: 12, fontWeight: 850 }}>{appealStatusLabel(status.appeal.status)}</span>}
          </div>
          {status.appeal?.admin_reply && <div style={replyStyle}><strong>管理员回复：</strong>{status.appeal.admin_reply}</div>}
          {(!status.appeal || status.appeal.status === 'needs_info' || ['approved', 'rejected', 'withdrawn'].includes(status.appeal.status)) && (
            <form onSubmit={submitAppeal} style={{ display: 'grid', gap: 12, marginTop: 14 }}>
              <label style={labelStyle}>申诉说明
                <textarea value={content} onChange={event => setContent(event.target.value)} rows={6} maxLength={2000} placeholder="说明限制可能存在的问题、相关时间和希望如何处理，至少 10 个字。" style={textareaStyle} />
              </label>
              <label style={labelStyle}>补充材料链接（可选，每行一个，最多 6 个）
                <textarea value={evidenceText} onChange={event => setEvidenceText(event.target.value)} rows={3} placeholder="https://..." style={textareaStyle} />
              </label>
              <button type="submit" disabled={submitting || content.trim().length < 10} style={buttonStyle(submitting || content.trim().length < 10)}>{submitting ? '提交中...' : status.appeal?.status === 'needs_info' ? '补充并重新提交' : '提交申诉'}</button>
            </form>
          )}
          {status.appeal?.status === 'pending' && <p style={bodyStyle}>申诉正在处理中。处理结果会出现在下方通知中，不需要重复提交。</p>}
        </section>
      )}

      <section style={panelStyle}>
        <h2 style={titleStyle}>账号通知</h2>
        {notices.length === 0 ? <p style={bodyStyle}>暂无账号治理通知。</p> : (
          <div style={{ display: 'grid', gap: 0, marginTop: 10 }}>
            {notices.map(item => (
              <button key={item.id} type="button" onClick={() => !item.read_at && void markRead(item.id)} style={{ display: 'grid', gap: 4, width: '100%', padding: '12px 0', border: 0, borderTop: '1px solid rgba(31,41,55,0.08)', background: 'transparent', color: INK, textAlign: 'left', cursor: item.read_at ? 'default' : 'pointer' }}>
                <span style={{ fontSize: 13, fontWeight: item.read_at ? 750 : 900 }}>{item.title}{!item.read_at ? ' · 未读' : ''}</span>
                <span style={{ color: MUTED, fontSize: 12, lineHeight: 1.65 }}>{item.content}</span>
                <span style={{ color: 'rgba(71,85,105,0.55)', fontSize: 11 }}>{dateTime(item.created_at)}</span>
              </button>
            ))}
          </div>
        )}
      </section>
    </JumuluPageFrame>
  );
}

const panelStyle: React.CSSProperties = { padding: '16px 18px', border: `1px solid ${LINE}`, borderRadius: 8, background: '#fff', color: INK };
const titleStyle: React.CSSProperties = { margin: 0, color: INK, fontSize: 16, fontWeight: 900 };
const bodyStyle: React.CSSProperties = { margin: '10px 0 0', color: MUTED, fontSize: 13, lineHeight: 1.75 };
const labelStyle: React.CSSProperties = { display: 'grid', gap: 7, color: INK, fontSize: 13, fontWeight: 850 };
const textareaStyle: React.CSSProperties = { width: '100%', boxSizing: 'border-box', resize: 'vertical', padding: '10px 12px', borderRadius: 8, border: '1px solid rgba(31,41,55,0.14)', background: '#fff', color: INK, font: 'inherit', fontWeight: 500, lineHeight: 1.65 };
const replyStyle: React.CSSProperties = { marginTop: 12, padding: '10px 12px', borderRadius: 7, background: '#eff6ff', color: '#275389', fontSize: 13, lineHeight: 1.7 };
const primaryLinkStyle: React.CSSProperties = { display: 'inline-flex', marginTop: 14, minHeight: 36, alignItems: 'center', padding: '0 13px', borderRadius: 7, background: '#1f2937', color: '#fff', fontSize: 13, fontWeight: 900, textDecoration: 'none' };
const buttonStyle = (disabled: boolean): React.CSSProperties => ({ justifySelf: 'start', minHeight: 38, padding: '0 15px', border: 0, borderRadius: 7, background: disabled ? '#e5e7eb' : '#1f2937', color: disabled ? '#94a3b8' : '#fff', cursor: disabled ? 'not-allowed' : 'pointer', fontSize: 13, fontWeight: 900 });
